### ISSUE TITLE
Delete retweets and replies

### ISSUE THREAD

**Issue by jordanbaucke** [baruchiro/delete-tweets#1]
Much more straight forward than other apps I've seen around for this - and Twitter's API changes make it difficult to do a simple task. Any chance you want to support "Retweets" and "Replies" (as the HTML elements are different...)

**Comment by baruchiro** [comment]
Yes, I will try.

The selectors are not easy to use, and I didn't test my script because I don't want to delete my tweets 😁

**Comment by baruchiro** [comment]
@jordanbaucke Please check now, sorry for late
