### ISSUE TITLE
Doesn't delete tweets

### ISSUE THREAD

**Issue by hhamud** [baruchiro/delete-tweets#3]
I've run this script but it doesn't seem to actually delete any of the tweets despite being able to see the delete button being physically clicked. it also struggles with retweets and likes?

I did change the base link as it was linked to your account to my own.

**Comment by hhamud** [comment]
fixed it myself

**Comment by baruchiro** [comment]
What did you change to fix it?

**Comment by hhamud** [comment]
> What did you change to fix it?

I rewrote it in rust

**Comment by baruchiro** [comment]
Do you think your project is better than this?

If so, let's move to your project.

**Comment by hhamud** [comment]
> Do you think your project is better than this?
> 
> If so, let's move to your project.

I found out that there was no real benefit since twitter caps the amount of requests that you could even do
